<?php

########################################################################
# Extension Manager/Repository config file for ext: "redirects"
#
# Auto generated by Extension Builder 2012-03-14
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Redirect Management',
	'description' => '',
	'category' => 'misc',
	'author' => 'Michael Klapper',
	'author_email' => 'michael.klapper@aoemedia.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.4',
			'fluid' => '1.4',
			'typo3' => '4.6',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>